#数据源
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
 mvc:
  view:
   prefix: /WEB-INF/views/
   suffix: .jsp

server:
 port: 8080
 #项目名字
 context-path: /springboot